### ISSUE TITLE
crash when loading old world

### ISSUE THREAD

**Issue by Njet75** [Ri5ux/AMDXLib#1]
Get this crasch using AMDXLib 1.0.0.4
Also happening when creating new world.

Hope this helps

/Michael
 
[crash-2016-08-03_13.05.45-client.txt](https://github.com/Ri5ux/AMDXLib/files/399310/crash-2016-08-03_13.05.45-client.txt)

[2016-08-03-2.log.gz](https://github.com/Ri5ux/AMDXLib/files/399324/2016-08-03-2.log.gz)

**Comment by Ri5ux** [comment]
This crash has been fixed. Thanks for the report.
